pem_file = "./infoundr_identity.pem"
ic_url = "http://localhost:4943"
oc_public_key = "-----BEGIN PUBLIC KEY-----\nMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEW1Z0uDeQiWdgxlpsjmAfjPlSKtZT\nT1/7A3xcYeMq3mhUE4PHqLu4D+tdsE5ga+0jyh8PgfsnFBmxNE+F+nr2eg==\n-----END PUBLIC KEY-----\n"
port = 13457
python_api_url = "http://localhost:5005"
log_level = "INFO"
canister_id = "bkyz2-fmaaa-aaaaa-qaaaq" 