# The location of the pem file containing the private key which
# the InfoundrBot will use to sign requests to the IC
pem_file = "./infoundr_identity.pem"

# [optional]
# The url of the Internet Computer instance the bot is targeting.
# If not specified the mainnet IC url will be used.
ic_url = "http://localhost:8080"

# [optional]
# Public key component of the key used by OpenChat to sign the issued JWTs. This value
# can be obtained from the OC UI by visiting User Profile -> Advanced -> Bot client config.
# If not specified the mainnet OC public key will be used.
oc_public_key = "-----BEGIN PUBLIC KEY-----\nMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEtF0POnprzqIiX5CS95BECA0uX2Pe\nydHc8LpadWZx1WdILqPMYHMHin6ZHmpikHSP5Gyznq6AXQPNpit1LsmR4w==\n-----END PUBLIC KEY-----\n"

# The port the OC bot will listen for commands on
port = 13457

# URL of your Python API
python_api_url = "http://localhost:5005"

# Set the appropriate log level you'd like to record. Logs are recorded by the
# `tracing` crate. Allowed values: TRACE, DEBUG, INFO, WARN, ERROR.
log_level = "INFO"

# The canister ID of Infoundr Canister
canister_id = "bkyz2-fmaaa-aaaaa-qaaaq-cai"