pem_file = "./infoundr_identity.pem"
ic_url = "https://icp0.io"
port = 13457
oc_public_key = """
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEquEHzJr9605Oy796e4z7LKow46DV
NUnDOQWavi86vEhRAAfdbVh/Lgmxfi44LPb6S0wnCRm9kI/XdK1DYw2Eaw==
-----END PUBLIC KEY-----
"""
log_level = "INFO"
python_api_url = "http://154.38.174.112:5005" 
canister_id = "g7ko2-fyaaa-aaaam-qdlea-cai"