name: Deploy ICP Rust Agent

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Switch to mainnet canister ID
        run: |
          sed -i 's|// const CANISTER_ID: &str = "g7ko2-fyaaa-aaaam-qdlea-cai"; // mainnet|const CANISTER_ID: &str = "g7ko2-fyaaa-aaaam-qdlea-cai"; // mainnet|g' api/icp_rust_agent/src/main.rs
          sed -i 's|const CANISTER_ID: &str = "54ro3-xaaaa-aaaab-qac2q-cai"; // development|// const CANISTER_ID: &str = "54ro3-xaaaa-aaaab-qac2q-cai"; // development|g' api/icp_rust_agent/src/main.rs

      - name: Create .env file
        run: |
          echo "API_KEY=dV4DBSWqPM7AZi3VLMl90y0PFvbAogj0SPIjqnGFl1E=" > .env
          echo "BASE_URL=https://infoundr.com/" >> .env

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: 154.38.174.112
          username: root
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            tmux send-keys -t infoundr_storage_api C-c
            tmux send-keys -t infoundr_storage_api "cd /root/ai-agents-bots/api/icp_rust_agent && git pull origin main && echo 'CANISTER_ID=g7ko2-fyaaa-aaaam-qdlea-cai' > .env && echo 'API_KEY=dV4DBSWqPM7AZi3VLMl90y0PFvbAogj0SPIjqnGFl1E=' >> .env && echo 'BASE_URL=https://infoundr.com/' >> .env && cargo build && cargo run" C-m 